In [1]:
test = [
    "00576224",
    "2c737e39",
    "642d658d",
    "9b4c17c4",
    "cd3c21df",
    "009d5c81",
    "32e9702f",
    "64a7c07e",
    "9c56f360",
    "cf133acc",
    "00dbd492",
    "332efdb3",
    "66f2d22f",
    "9caba7c3",
    "d19f7514",
    "0692e18c",
    "3391f8c0",
    "67636eac",
    "9ddd00f0",
    "d2acf2cb",
    "070dd51e",
    "33b52de3",
    "6ad5bdfd",
    "a04b2602",
    "d37a1ef5",
    "09c534e7",
    "3490cc26",
    "6ea4a07e",
    "a3f84088",
    "d4c90558",
    "0bb8deee",
    "34b99a2b",
    "72207abc",
    "a59b95c0",
    "d5c634a2",
    "0c786b71",
    "358ba94e",
    "72a961c9",
    "a680ac02",
    "d94c3b52",
    "0d87d2a6",
    "37d3e8b2",
    "762cd429",
    "aa18de87",
    "da2b0fe3",
    "103eff5b",
    "3ed85e70",
    "79369cc6",
    "aab50785",
    "dc2e9a9d",
    "12422b43",
    "3ee1011a",
    "7953d61e",
    "ac0c5833",
    "dd2401ed",
    "13713586",
    "42918530",
    "7bb29440",
    "ac3e2b04",
    "de493100",
    "140c817e",
    "4364c1c4",
    "7c9b52a0",
    "ac605cbb",
    "e0fb7511",
    "14754a24",
    "456873bc",
    "7d1f7ee8",
    "ad7e01d0",
    "e133d23d",
    "15113be4",
    "45737921",
    "7ee1c6ea",
    "af22c60d",
    "e1baa8a4",
    "16b78196",
    "477d2879",
    "817e6c09",
    "b15fca0b",
    "e1d2900e",
    "17b80ad2",
    "48131b3c",
    "84db8fc4",
    "b1fc8b8e",
    "e21a174a",
    "17cae0c1",
    "48f8583b",
    "84f2aca1",
    "b4a43f3b",
    "e345f17b",
    "184a9768",
    "4aab4007",
    "8597cfd7",
    "b7cb93ac",
    "e41c6fd3",
    "1990f7a8",
    "4b6b68e5",
    "85b81ff1",
    "b7fb29bc",
    "e5790162",
    "19bb5feb",
    "4cd1b7b2",
    "8719f442",
    "ba9d41b8",
    "e619ca6e",
    "1a6449f1",
    "4e45f183",
    "891232d6",
    "baf41dbf",
    "e633a9e5",
    "1acc24af",
    "4f537728",
    "896d5239",
    "bcb3040b",
    "e681b708",
    "1c02dbbe",
    "4ff4c9da",
    "8a371977",
    "bd14c3bf",
    "e6de6e8f",
    "1c0d0a4b",
    "505fff84",
    "8b28cd80",
    "be03b35f",
    "e760a62e",
    "1d0a4b61",
    "50aad11f",
    "8dae5dfc",
    "bf32578f",
    "e7639916",
    "1d398264",
    "50f325b5",
    "8ee62060",
    "bf699163",
    "e7b06bea",
    "2037f2c7",
    "516b51b7",
    "8fbca751",
    "bf89d739",
    "e99362f0",
    "20981f0e",
    "5289ad53",
    "903d1b4a",
    "c074846d",
    "e9bb6954",
    "212895b5",
    "52fd389e",
    "9110e3c5",
    "c1990cce",
    "e9c9d9a1",
    "21f83797",
    "55059096",
    "917bccba",
    "c48954c1",
    "ea959feb",
    "25094a63",
    "551d5bf1",
    "93c31fbe",
    "c62e2108",
    "ea9794b1",
    "256b0a75",
    "55783887",
    "94133066",
    "c64f1187",
    "ef26cbf6",
    "2685904e",
    "5783df64",
    "94414823",
    "c663677b",
    "f0afb749",
    "2753e76c",
    "5833af48",
    "963f59bc",
    "c6e1b8da",
    "f21745ec",
    "27a77e38",
    "5b6cbef5",
    "96a8c0cd",
    "c87289bb",
    "f45f5ca7",
    "27f8ce4f",
    "5d2a5c43",
    "97239e3d",
    "c8b7cc0f",
    "f8be4b64",
    "281123b4",
    "62ab2642",
    "9772c176",
    "c97c0139",
    "fc754716",
    "292dd178",
    "62b74c02",
    "992798f6",
    "cad67732",
    "fd096ab6",
    "29700607",
    "639f5a19",
    "99306f82",
    "ccd554ac",
    "fe9372f3",
]

In [3]:
import json 

eval_challenges = "/home/mehron/giotto-llm/kaggle/input/arc-agi_evaluation_challenges.json"
eval_challenges_solution = "/home/mehron/giotto-llm/kaggle/input/arc-agi_evaluation_solutions.json"

test_challenges = {}
test_solutions = {}

with open(eval_challenges, "r") as f:
    eval_challenges = json.load(f)

with open(eval_challenges_solution, "r") as f:
    eval_solutions = json.load(f)

for key in eval_challenges:
    if key in test:
        test_challenges[key] = eval_challenges[key]
        test_solutions[key] = eval_solutions[key]

with open("/home/mehron/giotto-llm/kaggle/input/arc-agi_200_test_challenges.json", "w") as f:
    json.dump(test_challenges, f)

with open("/home/mehron/giotto-llm/kaggle/input/arc-agi_200_test_solutions.json", "w") as f:
    json.dump(test_solutions, f)

In [1]:
import json
from giotto_llm.consts import DEFAULT_ATTEMPT

all_tasks = "/home/mehron/giotto-llm/kaggle/input/arc-agi_full_challenges.json"
submission_dir = "/home/mehron/giotto-llm/bfs_llama_1B_notr_arc_augmented_v5_16_transforms_dfs_sampling_10/predictions/"

with open(all_tasks, "r") as f:
    all_tasks = json.load(f)

with open(f"{submission_dir}/submission.json", "r") as f:
    submission = json.load(f)

print(f"Original submission: {len(submission)}")

for task in all_tasks:
    if task not in submission:
        submission[task] = [{"attempt_1": DEFAULT_ATTEMPT, "attempt_2": DEFAULT_ATTEMPT} for _ in range(len(all_tasks[task]["test"]))]

print(f"Final submission: {len(submission)}")

with open(f"{submission_dir}/final_submission.json", "w") as f:
    json.dump(submission, f)

Original submission: 195
Final submission: 800


: 

In [1]:
import torch
x =  torch.tensor([1,2,3])

x.to('cuda')
print(x)


tensor([1, 2, 3])


In [15]:
x = torch.tensor([1,2,3])

torch.where(x == 2)[0]

tensor([1])

: 

In [1]:
import torch


x = [(1,2,3)]
y = x

del x
print(y)

[(1, 2, 3)]


: 

In [24]:
def pack_list_of_caches(self, caches, device="cuda"):
    # Input: List of caches each of which is a (tuple of layers, each layer is a tuple of tensors)
    # Output: Tuple of layers, each layer is a tuple of tensors, each tensor is a batched
    if not caches:
        return None
    
    output_cache = []
    for layer_cache in zip(*caches):
        output_cache.append(tuple(torch.cat(tesnors, dim=0) for tesnors in zip(*layer_cache)))
    return tuple(output_cache)

def unpack_cache(self, cache, device="cpu"):
    if not cache:
        return None
    batch_size = len(cache[0][0])
    return [tuple(tuple(tensor[i].unsqueeze(0).to(device) for tensor in layer_cache) for layer_cache in cache) for i in range(batch_size)]

In [23]:
import torch
unpack_cache_test = ((torch.tensor([[1,2,3], [-1,-2,-3]]), torch.tensor([[4,5,6], [-4, -5, -6]])), (torch.tensor([[7,8,9], [-7, -8, -9]]), torch.tensor([[10,11,12], [-10, -11, -12]])))
print(unpack_cache_test)
x = unpack_cache(unpack_cache_test)

((tensor([[ 1,  2,  3],
        [-1, -2, -3]]), tensor([[ 4,  5,  6],
        [-4, -5, -6]])), (tensor([[ 7,  8,  9],
        [-7, -8, -9]]), tensor([[ 10,  11,  12],
        [-10, -11, -12]])))


In [18]:
x

[((tensor([[1, 2, 3]]), tensor([[4, 5, 6]])),
  (tensor([[7, 8, 9]]), tensor([[10, 11, 12]]))),
 ((tensor([[-1, -2, -3]]), tensor([[-4, -5, -6]])),
  (tensor([[-7, -8, -9]]), tensor([[-10, -11, -12]])))]

In [26]:
z=pack_list_of_caches(x)

((tensor([[1, 2, 3]]), tensor([[4, 5, 6]])), (tensor([[-1, -2, -3]]), tensor([[-4, -5, -6]])))
[(tensor([[1, 2, 3]]), tensor([[-1, -2, -3]])), (tensor([[4, 5, 6]]), tensor([[-4, -5, -6]]))]
((tensor([[7, 8, 9]]), tensor([[10, 11, 12]])), (tensor([[-7, -8, -9]]), tensor([[-10, -11, -12]])))
[(tensor([[7, 8, 9]]), tensor([[-7, -8, -9]])), (tensor([[10, 11, 12]]), tensor([[-10, -11, -12]]))]


In [28]:
assert (z == unpack_cache_test).all()

RuntimeError: Boolean value of Tensor with more than one value is ambiguous

In [30]:
z

((tensor([[ 1,  2,  3],
          [-1, -2, -3]]),
  tensor([[ 4,  5,  6],
          [-4, -5, -6]])),
 (tensor([[ 7,  8,  9],
          [-7, -8, -9]]),
  tensor([[ 10,  11,  12],
          [-10, -11, -12]])))

In [31]:
unpack_cache_test

((tensor([[ 1,  2,  3],
          [-1, -2, -3]]),
  tensor([[ 4,  5,  6],
          [-4, -5, -6]])),
 (tensor([[ 7,  8,  9],
          [-7, -8, -9]]),
  tensor([[ 10,  11,  12],
          [-10, -11, -12]])))

: 